[debug] [2022-05-08T01:50:27.784Z] ----------------------------------------------------------------------
[debug] [2022-05-08T01:50:27.785Z] Command:       /home/sajib/.nvm/versions/node/v16.13.2/bin/node /home/sajib/.nvm/versions/node/v16.13.2/bin/firebase deploy
[debug] [2022-05-08T01:50:27.785Z] CLI Version:   10.7.1
[debug] [2022-05-08T01:50:27.786Z] Platform:      linux
[debug] [2022-05-08T01:50:27.786Z] Node Version:  v16.13.2
[debug] [2022-05-08T01:50:27.793Z] Time:          Sun May 08 2022 07:50:27 GMT+0600 (Bangladesh Standard Time)
[debug] [2022-05-08T01:50:27.794Z] ----------------------------------------------------------------------
[debug] 
[debug] [2022-05-08T01:50:27.869Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2022-05-08T01:50:27.869Z] > authorizing via signed-in user (sajibur.dev@gmail.com)
[debug] [2022-05-08T01:50:27.869Z] [iam] checking project warehouse-management-8e3e7 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2022-05-08T01:50:27.870Z] > refreshing access token with scopes: []
[debug] [2022-05-08T01:50:27.871Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2022-05-08T01:50:48.788Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2022-05-08T01:50:48.790Z] > refreshing access token with scopes: []
[debug] [2022-05-08T01:50:48.791Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2022-05-08T01:50:49.315Z] <<< HTTP RESPONSE 200 {"date":"Sun, 08 May 2022 01:50:49 GMT","pragma":"no-cache","expires":"Mon, 01 Jan 1990 00:00:00 GMT","cache-control":"no-cache, no-store, max-age=0, must-revalidate","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2022-05-08T01:50:49.340Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/warehouse-management-8e3e7 [none]
[debug] [2022-05-08T01:51:10.057Z] Failed to make request to https://firebase.googleapis.com/v1beta1/projects/warehouse-management-8e3e7
[debug] [2022-05-08T01:51:30.788Z] FirebaseError: Failed to make request to https://firebase.googleapis.com/v1beta1/projects/warehouse-management-8e3e7
    at RetryOperation._fn (/home/sajib/.nvm/versions/node/v16.13.2/lib/node_modules/firebase-tools/lib/apiv2.js:240:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: Failed to get Firebase project warehouse-management-8e3e7. Please make sure the project exists and your account has permission to access it.
[debug] [2022-05-08T02:02:24.292Z] ----------------------------------------------------------------------
[debug] [2022-05-08T02:02:24.293Z] Command:       /home/sajib/.nvm/versions/node/v16.13.2/bin/node /home/sajib/.nvm/versions/node/v16.13.2/bin/firebase deploy
[debug] [2022-05-08T02:02:24.294Z] CLI Version:   10.7.1
[debug] [2022-05-08T02:02:24.294Z] Platform:      linux
[debug] [2022-05-08T02:02:24.294Z] Node Version:  v16.13.2
[debug] [2022-05-08T02:02:24.307Z] Time:          Sun May 08 2022 08:02:24 GMT+0600 (Bangladesh Standard Time)
[debug] [2022-05-08T02:02:24.308Z] ----------------------------------------------------------------------
[debug] 
[debug] [2022-05-08T02:02:24.376Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2022-05-08T02:02:24.376Z] > authorizing via signed-in user (sajibur.dev@gmail.com)
[debug] [2022-05-08T02:02:24.376Z] [iam] checking project warehouse-management-8e3e7 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2022-05-08T02:02:24.385Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/warehouse-management-8e3e7:testIamPermissions [none]
[debug] [2022-05-08T02:02:24.385Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/warehouse-management-8e3e7:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2022-05-08T02:02:45.112Z] [iam] error while checking permissions, command may fail: FirebaseError: Failed to make request to https://cloudresourcemanager.googleapis.com/v1/projects/warehouse-management-8e3e7:testIamPermissions
[debug] [2022-05-08T02:02:45.116Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/warehouse-management-8e3e7 [none]
[debug] [2022-05-08T02:03:05.830Z] Failed to make request to https://firebase.googleapis.com/v1beta1/projects/warehouse-management-8e3e7
[debug] [2022-05-08T02:03:06.364Z] FirebaseError: Failed to make request to https://firebase.googleapis.com/v1beta1/projects/warehouse-management-8e3e7
    at RetryOperation._fn (/home/sajib/.nvm/versions/node/v16.13.2/lib/node_modules/firebase-tools/lib/apiv2.js:240:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: Failed to get Firebase project warehouse-management-8e3e7. Please make sure the project exists and your account has permission to access it.
